### ISSUE TITLE
Add switch for rendering JSON output

### ISSUE THREAD

**Issue by timjacobi** [harksys/npmvet#10]
It would be great to have a JSON renderer so you can store or process the output. Instead of a table the output could be something like
```json
[
  {
    "name": "blessed",
    "packageVersion": "0.1.81",
    "installedVersion": "0.1.81",
    "matches": true,
    "locked": false
  },
]
```

**Comment by juliankay** [comment]
That sounds like it would be a great addition 👍

**Comment by timjacobi** [comment]
I'm happy to send a PR if @andrewhathaway feels the same

**Comment by andrewhathaway** [comment]
Sure do! Looking forward to seeing the PR. :)
