### ISSUE TITLE
Fail CI if versions are not locked.

### ISSUE THREAD

**Issue by jameswlane** [harksys/npmvet#19]
There should be a flag you can add if packages are not locked it would fail the CI also.

**Comment by andrewhathaway** [comment]
@jameswlane Sure, but in terms of having a build published successfully you only want to check that packages match up? Unless you're thinking for other checks, like pull requests?

**Comment by jameswlane** [comment]
In our Jenkins environment we _should_ be clearing out the work space before building.
Once we pull everything down and verify all testing passes we use [bundle-dependencies](https://www.npmjs.com/package/bundle-dependencies) to package it up and pass it though our environments. It has happened before when it didn't clear properly and we like that `npmvet` will fail if there is a mismatch check.

We would also like if it fails if a package is unlocked. Currently we are regexing the output for unlocked and throwing a exit 1. It would be nice if the failure was built into npmvet itself.

**Comment by andrewhathaway** [comment]
Okay, sure thing! I'll put this on my list / PRs welcome.

**Comment by jameswlane** [comment]
👍 Awesome

**Comment by andrewhathaway** [comment]
Hi @jameswlane! Great news, just pushed v0.1.4 which includes the `-s` flag for this. More info on the README! :)

**Comment by jameswlane** [comment]
You are awesome sir! Thank you.
