### ISSUE TITLE
If package version is tgz it will be `Mismatch`

### ISSUE THREAD

**Issue by km-tr** [harksys/npmvet#2]
It seems that the installed version matches, but if package version is tgz it will be `Mismatch`.

```bash
example:
glob │ https://registry.npmjs.org/glob/-/glob-7.1.1.tgz │ 7.1.1   │  Mismatch  │  Unlocked
```

**Comment by andrewhathaway** [comment]
Thanks for the issue. I'll have to look further in to this, how to get the defined version etc.

**Comment by andrewhathaway** [comment]
>@zachallen, #15

>Currently if you have a package version referenced via git, npmvet will say the dependency is Mismatched & Unlocked

>For example (package.json):
"jquery-mask-plugin": "git+https://github.com/nmelv170/jQuery-Mask-Plugin.git#ec617bf82861401738027674e053ead8701bd10e"

**Comment by ozzyknox** [comment]
Hi, I am getting this same issue:

 happyid │ git+ssh://git@xxx.xxx.xyz:api-util/happyid.git#v1.0.0 │ 1.0.0             │  Mismatch  │  Unlocked

**Comment by andrewhathaway** [comment]
Hi @ozzyknox - This has been centralised in to issue #15 - Thanks!

**Comment by andrewhathaway** [comment]
Releasing 0.1.5 now, this will fix these issues!
