### ISSUE TITLE
Handling sub-dependencies

### ISSUE THREAD

**Issue by steveharrison** [harksys/npmvet#21]
How does this handle sub-dependencies (i.e. you're not locking down`babel` if you remove the `^` in your project's `package.json` because that version of Babel still uses the caret to specify its dependencies) ?

And what benefit does this tool provide over using `npm shrinkwrap`?

**Comment by andrewhathaway** [comment]
Hi @steveharrison,

This package doesn't account for sub-packages, we're working on a top-level basis for your project. I do however see how this could potentially be useful, given your example.

As for "NPM Vet vs shrinkwrap", they are for a completely different purpose. The main purpose for NPM Vet is for a quick visual-reference to see whether your projects packages are "locked down", and what versions you are currently running. Apart from that, and the CI integration, thats what it does. Hope that clears things up!
