### ISSUE TITLE
Pipeline does not fail with ci renderer when there is a mismatch

### ISSUE THREAD

**Issue by laurinenas** [harksys/npmvet#34]
Hey,

First of all, thanks for amazing project!

I have added `npmvet -r ci ` to pipeline hoping it would start failing the pipeline if there is a version mismatch. There is a new mismatch, but the pipeline does not fail and the command has exited with 0 error code.

Am I using it not in a proper way?

Thanks for your answer!

**Comment by andrewhathaway** [comment]
Hi @laurinenas! Can you try with the `-s` flag added too please, that enables strict mode we should fix the problem.

**Comment by laurinenas** [comment]
Hey thanks @andrewhathaway for the response!

If that is any help we are running npmvet v0.2.0 on bitbucket pipelines. Both:
`- npx npmvet -r -s ci` and
`- npx npmvet -rs ci`

got a 0 return code, i.e. green pipeline.


Am I using it correctly?

**Comment by andrewhathaway** [comment]
@laurinenas I haven't used it with Bitbucket Pipelines but we've been running this in Production on Azure Pipelines for multiple years with the following: `npmvet -r ci -s`.

The issue with your commands above is that -r (renderer flag) has an argument (`ci`) which is required directly after `-r`.

**Comment by slieschke** [comment]
The command line arguments are getting ignored in the v0.2.0 release, I've submitted a PR that fixes this at #37.

**Comment by andrewhathaway** [comment]
Thank you @slieschke! I have released v0.2.1 now with your fix - @laurinenas this should also resolve your issue!
