### ISSUE TITLE
What does "Locked" mean?

### ISSUE THREAD

**Issue by SxMShaDoW** [harksys/npmvet#4]
Aren't you "locking" it when you use `~` or `^` ? 

Or is it only supposed to represent if you use a static version?

**Comment by andrewhathaway** [comment]
Hi @SxMShaDoW.

If you use a tilde or caret, then the version is not locked. This mean is it prone to not installing the exact version you defined. This is completely acceptable by design.

More information here: https://harksys.com/labs/npm-vet-a-simple-cli-tool-for-checking-npm-package-versions/
