### ISSUE TITLE
Contributing steps problems

### ISSUE THREAD

**Issue by timjacobi** [harksys/npmvet#6]
Hi

I just forked, cloned and followed the steps in https://github.com/harksys/npmvet/blob/master/CONTRIBUTING.md

After the `npm install` step npm runs the `prepublish` script which attempts to build the lib. This fails if the typings are not installed so ideally the `typings install` step should come before the `npm install` step.

**Comment by andrewhathaway** [comment]
Ahh good point! I'll have to update the contributing.md doc, unless you fancy submitting a PR? :D

**Comment by timjacobi** [comment]
Please have a look at #7 which should allow for the `typings install` step to be removed completely.

**Comment by andrewhathaway** [comment]
Okay. Closing this issue due to other issue opened.
