### ISSUE TITLE
Usage of typings for TS type management

### ISSUE THREAD

**Issue by timjacobi** [harksys/npmvet#7]
I realise the types for this package are managed by `typings`. Since TypeScript 2 you can manage types using NPM and the @types organisation - [see here](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/).

I have tested this locally and am happy to submit a PR if this is of interest.

**Comment by andrewhathaway** [comment]
That sounds great, I'll take a look at the PR!
